package clasesZoo;
// Generated 14-feb-2022 13:47:46 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Alimento generated by hbm2java
 */
public class Alimento implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private double coste;
	private Set consumes = new HashSet(0);

	public Alimento() {
	}

	public Alimento(String descripcion, double coste) {
		this.descripcion = descripcion;
		this.coste = coste;
	}

	public Alimento(String descripcion, double coste, Set consumes) {
		this.descripcion = descripcion;
		this.coste = coste;
		this.consumes = consumes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getCoste() {
		return this.coste;
	}

	public void setCoste(double coste) {
		this.coste = coste;
	}

	public Set getConsumes() {
		return this.consumes;
	}

	public void setConsumes(Set consumes) {
		this.consumes = consumes;
	}

}
