package clasesZoo;
// Generated 14-feb-2022 13:47:46 by Hibernate Tools 4.0.1.Final

/**
 * Animaltratamiento generated by hbm2java
 */
public class Animaltratamiento implements java.io.Serializable {

	private AnimaltratamientoId id;
	private Animal animal;
	private Empleado empleado;
	private Tratamiento tratamiento;

	public Animaltratamiento() {
	}

	public Animaltratamiento(AnimaltratamientoId id, Animal animal, Empleado empleado, Tratamiento tratamiento) {
		this.id = id;
		this.animal = animal;
		this.empleado = empleado;
		this.tratamiento = tratamiento;
	}

	public AnimaltratamientoId getId() {
		return this.id;
	}

	public void setId(AnimaltratamientoId id) {
		this.id = id;
	}

	public Animal getAnimal() {
		return this.animal;
	}

	public void setAnimal(Animal animal) {
		this.animal = animal;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Tratamiento getTratamiento() {
		return this.tratamiento;
	}

	public void setTratamiento(Tratamiento tratamiento) {
		this.tratamiento = tratamiento;
	}

}
