package clasesZoo;
// Generated 14-feb-2022 13:47:46 by Hibernate Tools 4.0.1.Final

/**
 * Consume generated by hbm2java
 */
public class Consume implements java.io.Serializable {

	private ConsumeId id;
	private Animal animal;
	private Alimento alimento;
	private int cantidadDia;

	public Consume() {
	}

	public Consume(ConsumeId id, Animal animal, Alimento alimento, int cantidadDia) {
		this.id = id;
		this.animal = animal;
		this.alimento = alimento;
		this.cantidadDia = cantidadDia;
	}

	public ConsumeId getId() {
		return this.id;
	}

	public void setId(ConsumeId id) {
		this.id = id;
	}

	public Animal getAnimal() {
		return this.animal;
	}

	public void setAnimal(Animal animal) {
		this.animal = animal;
	}

	public Alimento getAlimento() {
		return this.alimento;
	}

	public void setAlimento(Alimento alimento) {
		this.alimento = alimento;
	}

	public int getCantidadDia() {
		return this.cantidadDia;
	}

	public void setCantidadDia(int cantidadDia) {
		this.cantidadDia = cantidadDia;
	}

}
