package clasesZoo;
// Generated 14-feb-2022 13:47:46 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Date fechaNac;
	private String direccion;
	private Set nominas = new HashSet(0);
	private Set animaltratamientos = new HashSet(0);
	private Set tratamientos = new HashSet(0);
	private Set zonas = new HashSet(0);

	public Empleado() {
	}

	public Empleado(String nombre, Date fechaNac, String direccion) {
		this.nombre = nombre;
		this.fechaNac = fechaNac;
		this.direccion = direccion;
	}

	public Empleado(String nombre, Date fechaNac, String direccion, Set nominas, Set animaltratamientos,
			Set tratamientos, Set zonas) {
		this.nombre = nombre;
		this.fechaNac = fechaNac;
		this.direccion = direccion;
		this.nominas = nominas;
		this.animaltratamientos = animaltratamientos;
		this.tratamientos = tratamientos;
		this.zonas = zonas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set getNominas() {
		return this.nominas;
	}

	public void setNominas(Set nominas) {
		this.nominas = nominas;
	}

	public Set getAnimaltratamientos() {
		return this.animaltratamientos;
	}

	public void setAnimaltratamientos(Set animaltratamientos) {
		this.animaltratamientos = animaltratamientos;
	}

	public Set getTratamientos() {
		return this.tratamientos;
	}

	public void setTratamientos(Set tratamientos) {
		this.tratamientos = tratamientos;
	}

	public Set getZonas() {
		return this.zonas;
	}

	public void setZonas(Set zonas) {
		this.zonas = zonas;
	}

}
