package clasesZoo;
// Generated 14-feb-2022 13:47:46 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Entrada generated by hbm2java
 */
public class Entrada implements java.io.Serializable {

	private Integer id;
	private Evento evento;
	private Date fechaHoraVenta;

	public Entrada() {
	}

	public Entrada(Evento evento, Date fechaHoraVenta) {
		this.evento = evento;
		this.fechaHoraVenta = fechaHoraVenta;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Date getFechaHoraVenta() {
		return this.fechaHoraVenta;
	}

	public void setFechaHoraVenta(Date fechaHoraVenta) {
		this.fechaHoraVenta = fechaHoraVenta;
	}

}
