package clasesZoo;
// Generated 14-feb-2022 13:47:46 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Especie generated by hbm2java
 */
public class Especie implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private Set animals = new HashSet(0);

	public Especie() {
	}

	public Especie(String descripcion) {
		this.descripcion = descripcion;
	}

	public Especie(String descripcion, Set animals) {
		this.descripcion = descripcion;
		this.animals = animals;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getAnimals() {
		return this.animals;
	}

	public void setAnimals(Set animals) {
		this.animals = animals;
	}

}
