package clasesZoo;
// Generated 14-feb-2022 13:47:46 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private double precio;
	private Date horaInicio;
	private Date horaFin;
	private Set entradas = new HashSet(0);

	public Evento() {
	}

	public Evento(String descripcion, double precio) {
		this.descripcion = descripcion;
		this.precio = precio;
	}

	public Evento(String descripcion, double precio, Date horaInicio, Date horaFin, Set entradas) {
		this.descripcion = descripcion;
		this.precio = precio;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.entradas = entradas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	public Set getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set entradas) {
		this.entradas = entradas;
	}

}
