package clasesZoo;
// Generated 14-feb-2022 13:47:46 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Nomina generated by hbm2java
 */
public class Nomina implements java.io.Serializable {

	private int id;
	private Empleado empleado;
	private Date fechaEmision;
	private double importeBruto;
	private double irpf;
	private double segSocial;

	public Nomina() {
	}

	public Nomina(int id, Empleado empleado, Date fechaEmision, double importeBruto, double irpf, double segSocial) {
		this.id = id;
		this.empleado = empleado;
		this.fechaEmision = fechaEmision;
		this.importeBruto = importeBruto;
		this.irpf = irpf;
		this.segSocial = segSocial;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public double getImporteBruto() {
		return this.importeBruto;
	}

	public void setImporteBruto(double importeBruto) {
		this.importeBruto = importeBruto;
	}

	public double getIrpf() {
		return this.irpf;
	}

	public void setIrpf(double irpf) {
		this.irpf = irpf;
	}

	public double getSegSocial() {
		return this.segSocial;
	}

	public void setSegSocial(double segSocial) {
		this.segSocial = segSocial;
	}

}
