package clasesZoo;
// Generated 14-feb-2022 13:47:46 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tratamiento generated by hbm2java
 */
public class Tratamiento implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private double coste;
	private Set animaltratamientos = new HashSet(0);
	private Set empleados = new HashSet(0);

	public Tratamiento() {
	}

	public Tratamiento(String descripcion, double coste) {
		this.descripcion = descripcion;
		this.coste = coste;
	}

	public Tratamiento(String descripcion, double coste, Set animaltratamientos, Set empleados) {
		this.descripcion = descripcion;
		this.coste = coste;
		this.animaltratamientos = animaltratamientos;
		this.empleados = empleados;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getCoste() {
		return this.coste;
	}

	public void setCoste(double coste) {
		this.coste = coste;
	}

	public Set getAnimaltratamientos() {
		return this.animaltratamientos;
	}

	public void setAnimaltratamientos(Set animaltratamientos) {
		this.animaltratamientos = animaltratamientos;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

}
