package clasesZoo;
// Generated 14-feb-2022 13:47:46 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Zona generated by hbm2java
 */
public class Zona implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private Set animals = new HashSet(0);
	private Set empleados = new HashSet(0);

	public Zona() {
	}

	public Zona(String descripcion) {
		this.descripcion = descripcion;
	}

	public Zona(String descripcion, Set animals, Set empleados) {
		this.descripcion = descripcion;
		this.animals = animals;
		this.empleados = empleados;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getAnimals() {
		return this.animals;
	}

	public void setAnimals(Set animals) {
		this.animals = animals;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

}
